username: "r"
email: "reginaldbeakes@gmail.com"
ssh_key_filename: "id_rsa"
config: "{{ lookup('ansible.builtin.env', 'XDG_CONFIG') }}"
home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
personal: "{{ home }}/personal"
